apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: testspringboot
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testspringboot
        track: stable
    spec:
      containers:
      - name: testspringboot
        image: registry.howdohr.com/testspringboot:${CICD_EXECUTION_SEQUENCE}
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: testspringboot
spec:
  type: NodePort
  selector:
    app: testspringboot
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

