spring:
  redis:
    host: redis-master.redis
    password: 123456
  ## 数据源
  datasource:
    ## mysql链接驱动，可不配置。默认从引入的pom中找
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    ## 批量更新sql需要设置&allowMultiQueries=true
    url: jdbc:mysql://mysql8.mysql:3306/test?characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    ## 连接池，可不配置。2.x默认使用该连接池
    type: com.zaxxer.hikari.HikariDataSource
    ## 每次启动都会执行初始化表的sql，如果不需要，删除
    initialization-mode: always
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql

## mybatiplus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.example.demo.pojo.entity

# 日志输出，不配置不会输出sql日志
logging:
  level:
    com.example.demo: debug
